export interface TerceroCreateDTO {
  id?: string; 
  tipoPersonaId: number;
  tipoIdentificacionId: number;
  identificacion: string;
  dv?: string;
  nombres?: string;
  apellidos?: string;
  nombreComercial?: string;
  email?: string | null;
  colegioId: string;
  categoriaIds: number[];
  regimenIvaId: number;
  departamentoId?: number | null;
  municipioId?: number | null;
  direccion?: string | null;
  telefono?: string | null;
  indicativo?: string;
  codigoPostal?: string; 
  contactoNombres?: string; 
  contactoApellidos?: string; 
  correoFacturacion?: string; 
  responsabilidadesFiscalesIds: number[];
  activo?: boolean;
}
export interface TerceroUpdateDTO {
  id: string; 
  tipoPersonaId: number;
  tipoIdentificacionId: number;
  identificacion: string;
  dv?: string;
  nombres?: string;
  apellidos?: string;
  nombreComercial?: string;
  email?: string | null;
  colegioId: string;
  categoriaIds: number[];
  regimenIvaId: number;
  departamentoId?: number | null;
  municipioId?: number | null;
  direccion?: string | null;
  telefono?: string | null;
  indicativo?: string;
  codigoPostal?: string; 
  contactoNombres?: string; 
  contactoApellidos?: string; 
  correoFacturacion?: string; 
  responsabilidadesFiscalesIds: number[];
  activo?: boolean;
}
